Add Fuel Detotalizer Switch to the Mirage 2000C Fuel Panel
HeliosVirtualCockpit/Helios pull request #417
Opened 2021-05-07 08:04 UTC by norsetto

Hi again,

I added the Fuel Detotalizer switch to the Mirage 2000C Fuel Panel. Unfortunately I couldn't figure out a way to add the bindings if not manually via the Profile Editor. Could this be of interest to you, and if so, could you perhaps advise me on how to add the bindings directly?

2021-05-10 14:24 UTC, derammo commented
what you have there should theoretically work.  However, the "CompositeVisual" stuff is a horrible mess where people repeatedly copied the same code to a bunch of classes, so it is very likely broken somewhere.   You will need to step through the code to see why it doesn't populate the default bindings correctly.   There are other, very similar switches in there you could verify first to make sure stuff is working.   If you can't get it worked out, let me know and I will spin up on this.

2021-05-12 14:43 UTC, norsetto commented
I suspect that this is because the declutter switch is a momentary switch.

2021-08-01 17:41 UTC, derammo commented
@norsetto I can't find your Discord info, can you friend me on Discord please?

2021-08-01 17:53 UTC, derammo requested changes

2021-08-01 17:53 UTC, derammo commented on Helios/Gauges/M2000C/PCNPanel/PCN_Panel.cs
> +            //AddIndicatorPushButton("Offset Waypoint/Target", "enc", new Point(column1, row1), new Size(58, 40));
please add a comment why this is removed to clarify to the next reader

2021-08-01 17:53 UTC, derammo commented on Helios/Interfaces/DCS/M2000C/M2000CInterface.cs
> +            //AddFunction(new PushButton(this, PCN_NAV, "3667", "667", "PCN Panel", "Offset Waypoint/Target Button"));
please add a comment why this is removed

2021-08-01 17:53 UTC, derammo commented on Helios/Interfaces/DCS/M2000C/M2000CInterface.cs
> +            //AddFunction(new FlagValue(this, "668", "PCN Panel", "Offset Waypoint/Target", "ENC"));
please add a comment why this is removed

2021-08-04 17:34 UTC, norsetto commented
No problem, I added comments as well as removed two unused variables which were left from the change.

2021-08-04 23:02 UTC, derammo approved these changes

2021-08-04 23:03 UTC, merged